# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 7
  labels:
    k8s-app: fahrzeugvermietung-backend
  name: fahrzeugvermietung-backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fahrzeugvermietung-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fahrzeugvermietung-backend
      name: fahrzeugvermietung-backend
    spec:
      containers:
      - image: ghcr.io/smart-city-sose-2022/fahrzeugvermietung-backend:main
        name: fahrzeugvermietung-backend
        envFrom:
        - configMapRef:
          name: fahrzeugvermietung-backend
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: github-docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
