kind: Service
apiVersion: v1
metadata:
  name: fahrzeugvermietung-backend
  namespace: default
  labels:
    k8s-app: fahrzeugvermietung-backend
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2022-05-09T09:53:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:k8s-app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":9002,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
spec:
  ports:
    - name: tcp-9002-5000-8hx9p
      protocol: TCP
      port: 9002
      targetPort: 5000
  selector:
    k8s-app: fahrzeugvermietung-backend
  clusterIP: 10.109.232.130
  clusterIPs:
    - 10.109.232.130
  type: LoadBalancer
  externalIPs:
    - 217.160.47.130
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
